# Generated by Django 4.2.3 on 2023-08-25 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct_messages', '0002_alter_chattingroom_users_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattingroom',
            name='users',
            field=models.ManyToManyField(related_name='chattin_grooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
